######################## default configuration ####################
baseURL = "https://ea1fid.github.io/"
title = "FIDtenas | Open-source RF hardware for Amateur Radio"
theme = "bookworm-light"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "G-RFVXC87BGV" # example : UA-123-45
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com


############################# A ver ################################

[taxonomies]
category = "categories"
  tag = "tags"
  band = "bands"
  model = "models"



############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################
[imaging]
quality = "95"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

#################### default parameters ################################
[params]
logo = "images/logo_v4.3.png"
logo_width = "300px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Pablo EA1FID"
# contact form action
contact_form_action = "https://formspree.io/f/xzbyjbkl" # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Designs and images are copyrrighted by Pablo EA1FID"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "bookworm"
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################

#[[menu.main]]
#weight = 1
#url = "/"
#name = "Home"

[[menu.main]]
weight = 1
url = "august23"
name = "?"

[[menu.main]]
weight = 2
name = "  "

[[menu.main]]
weight = 3
url = "#"
name = "FIDtennas"
hasChildren = true

  [[menu.main]]
  parent = "FIDtennas"
  weight = 1
  url = "/"
  name = "All"
    
  [[menu.main]]
  parent = "FIDtennas"
  weight = 2
  url = "bands/"
  name = "By frequency band"
  
  [[menu.main]]
  parent = "FIDtennas"
  weight = 3
  url = "models/"
  name = "By type"
  
  [[menu.main]]
  parent = "FIDtennas"
  weight = 4
  url = "categories/"
  name = "By use"
  
[[menu.main]]
weight = 4
name = " "

[[menu.main]]
weight = 5
url = "#"
name = "EA1FID"
hasChildren = true

  [[menu.main]]
  parent = "EA1FID"
  weight = 1
  url = "about"
  name = "About FIDtenas"
  
  [[menu.main]]
  parent = "EA1FID"
  weight = 2
  url = "author/"
  name = "About me"  

  [[menu.main]]
  parent = "EA1FID"
  weight = 3
  url = "https://www.qrz.com/db/EA1FID"
  name = "QRZ"
  
  [[menu.main]]
  parent = "EA1FID"
  weight = 4
  url = "contact"
  name = "Contact"
  
  [[menu.main]]
  parent = "EA1FID"
  weight = 5
  url = "support/"
  name = "Contribute"


#[[menu.main]]
#weight = 4
#url = "about"
#name = "About"







############################# Footer Menu ########################
[[menu.footer]]
weight = 1
url = "about/"
name = "About FIDtenas"

[[menu.footer]]
weight = 2
url = "author/ea1fid/"
name = "About EA1FID"

[[menu.footer]]
weight = 3
url = "contact"
name = "Contact"

[[menu.footer]]
weight = 4
url = "support/"
name = "Support this project"

#[[menu.footer]]
#weight = 3
#url = "privacy/"
#name = "Privacy"

#[[menu.footer]]
#weight = 4
#url = "terms-conditions/"
#name = "Terms & Conditions"

# Social Icons

#[[params.social]]
#url = "https://www.facebook.com/fidtenas"
#icon = "lab la-facebook-f" # https://icons8.com/line-awesome

[[params.social]]
url = "https://www.twitter.com/ea1fid"
icon = "lab la-twitter" # https://icons8.com/line-awesome

#[[params.social]]
#url = "https://www.qrz.com/db/EA1FID"
#icon = "las la-satellite-dish" # https://icons8.com/line-awesome

[[params.social]]
url = "https://www.qrz.com/db/EA1FID"
icon = "las la-broadcast-tower" # https://icons8.com/line-awesome

[[params.social]]
url = "https://es.linkedin.com/in/p-adominguez"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome

[[params.social]]
url = "https://github.com/pepassaco/FIDtennas"
icon = "lab la-github" # https://icons8.com/line-awesome